version: '3'

services:
  adminer:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
  redis:
    image: redis
    ports:
    - 6379:6379
  authenticationDatabase:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    security_opt:
      - seccomp:unconfined